name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Package
        run: |
          cd ${{github.workspace}}/build
          cpack -C Release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{github.workspace}}/build/MultiConnect-*-win64.exe
            ${{github.workspace}}/build/MultiConnect-*-win64.zip
